name: "[Feature] Terraform Validate Feature Branch Pipeline"
run-name: User ${{ github.actor }} is validating terraform on branch ${{ github.ref }}
on:
  push:
    branches:    
      - 'feature/**'
jobs:
  reuse-workflow:
    uses: paulosobral/amp-02-infra-reusable/.github/workflows/simple-infra-validate-terraform.yml@v1.0